name: Build ForgeRock Android SDK
on:
  # Trigger on every pull request and on push
  # to the `develop` branch.
  pull_request:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest
    # strategy:
    #   matrix:
    #     api-level: [21, 23, 29]
    #     target: [default,google_apis]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Add google-services.json to the project
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $GOOGLE_SERVICES >> samples/authenticator/google-services.json

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Instrumentation Tests
        run: ./gradlew assembleDebug

      - name: Upload forgerock-auth-debug-androidTest.apk
        uses: actions/upload-artifact@v2
        with:
          name: forgerock-auth-debug-androidTest.apk
          path: forgerock-auth/build/outputs/forgerock-auth-debug-androidTest.apk

      - name: Upload auth-debug.apk
        uses: actions/upload-artifact@v2
        with:
          name: auth-debug.apk
          path: auth/build/outputs/apk/auth-debug.apk
      
      - name: Run unit tests
        run: ./gradlew test --stacktrace

      # - name: Instrumentation Tests
      #
      #   uses: reactivecircus/android-emulator-runner@v2.22.0
      #   with:
      #     api-level: ${{ matrix.api-level }}
      #     target: ${{ matrix.target }}
      #     arch: x86
      #     profile: Nexus 6
      #     script: ./gradlew connectedCheck --stacktrace

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: forgerock-auth/build/test-results/testDebugUnitTest 
        if: always()